version: '3'
services:
  app:
    hostname: app
    build: ./app
    working_dir: '/go/src/app'
    command: sh ./start_cmd.sh
    volumes:
      - ./app:/go/src/app
      - ./common/pb:/go/src/app/pb
    ports:
      - 8080:5000
    tty: true
  web:
    hostname: web
    build: ./web
    working_dir: '/src/web'
    command: sh ./web/start_cmd.sh
    volumes:
      - .:/src/web
      - ./common/pb:/src/web/pb
    ports:
      - 3000:3000
    links:
      - app
    tty: true

