version: '3'
services:
  server_go:
    hostname: server_go
    build: server_go
    working_dir: '/go/src/app'
    command: sh ./start_cmd.sh
    volumes:
      - ./server_go:/go/src/app
      - ./proto:/go/src/proto
    ports:
      - 5000:5000
    tty: true
  client_go:
    hostname: client_go
    build: client_go
    working_dir: '/go/src/web'
    command: sh ./start_cmd.sh
    volumes:
      - ./client_go:/go/src/web
      - ./proto:/go/src/proto
    ports:
      - 8080:8080
    links:
      - server_go
    tty: true
