version: '3'
services:
  server_go:
    hostname: server_go
    build: server_go
    working_dir: '/go/src/app'
    command: sh ./start_cmd.sh
    volumes:
      - ./server_go:/go/src/app
      - ./proto:/go/src/proto
    ports:
      - 5000:5000
    tty: true

